CREATE TABLE IF NOT EXISTS users
(
    id                  int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    google_id,          TEXT
    email               TEXT,
    username            TEXT,
    profile_picture_url TEXT,
);